version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo-app-db-1
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: todo-app-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admindb
      DB_PASSWORD: adminpassword
      DB_NAME: todo_db

  nginx:
    image: nginx:latest
    container_name: todo-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data: